DROP TRIGGER IF EXISTS refundPledges ON PROJECT;
DROP FUNCTION IF EXISTS autoRefundProjects;

DROP TRIGGER IF EXISTS checkReportHandling ON PROJECT_REPORT;
DROP FUNCTION IF EXISTS handleProjectCheck;

DROP TRIGGER IF EXISTS checkPledgesAmt ON PLEDGING_PLEDGES;
DROP FUNCTION IF EXISTS checkProjectLimit;

DROP TRIGGER IF EXISTS createInsertProjectLog ON PROJECT;
DROP TRIGGER IF EXISTS createUpdateProjectLog ON PROJECT;
DROP TRIGGER IF EXISTS createDeleteProjectLog ON PROJECT;
DROP TRIGGER IF EXISTS createInsertUserLog ON USER_ACC;
DROP TRIGGER IF EXISTS createUpdateUserLog ON USER_ACC;
DROP TRIGGER IF EXISTS createDeleteUserLog ON USER_ACC;
DROP FUNCTION IF EXISTS addLogging;
DROP FUNCTION IF EXISTS logging;

DROP TRIGGER IF EXISTS checkPledgesDate ON PLEDGING_PLEDGES;
DROP FUNCTION IF EXISTS checkProjectDate;

DROP TABLE IF EXISTS PROJECT_COMMENT;
DROP TABLE IF EXISTS TAGGED_TO_TAG;
DROP TABLE IF EXISTS PLEDGING_PLEDGES;
DROP TABLE IF EXISTS PROJECT_REPORT;

DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS USER_ACC;

DROP TABLE IF EXISTS LOGGING;